In [3]:
import numpy as np
import pandas as pd

In [33]:
df=pd.read_csv("Amazon Sale Report.csv")

In [34]:
df.head()

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Category,Size,Courier Status,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,B2B,fulfilled-by,New,PendingS
0,0,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Standard,T-shirt,S,On the Way,...,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,False,Easy Ship,NaN,NaN
1,1,171-9198151-1101146,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,Shirt,3XL,Shipped,...,INR,406.00,BENGALURU,KARNATAKA,560085.0,IN,False,Easy Ship,NaN,NaN
2,2,404-0687676-7273146,04-30-22,Shipped,Amazon,Amazon.in,Expedited,Shirt,XL,Shipped,...,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,True,NaN,NaN,NaN
3,3,403-9615377-8133951,04-30-22,Cancelled,Merchant,Amazon.in,Standard,Blazzer,L,On the Way,...,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,False,Easy Ship,NaN,NaN
4,4,407-1069790-7240320,04-30-22,Shipped,Amazon,Amazon.in,Expedited,Trousers,3XL,Shipped,...,INR,574.00,CHENNAI,TAMIL NADU,600073.0,IN,False,NaN,NaN,NaN

In [53]:
df.tail()

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Category,Size,Courier Status,Qty,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,B2B,fulfilled-by
128971,128970,406-6001380-7673107,05-31-22,Shipped,Amazon,Amazon.in,Expedited,Shirt,XL,Shipped,1,INR,517.0,HYDERABAD,TELANGANA,500013.0,IN,False,Unknown
128972,128971,402-9551604-7544318,05-31-22,Shipped,Amazon,Amazon.in,Expedited,T-shirt,M,Shipped,1,INR,999.0,GURUGRAM,HARYANA,122004.0,IN,False,Unknown
128973,128972,407-9547469-3152358,05-31-22,Shipped,Amazon,Amazon.in,Expedited,Blazzer,XXL,Shipped,1,INR,690.0,HYDERABAD,TELANGANA,500049.0,IN,False,Unknown
128974,128973,402-6184140-0545956,05-31-22,Shipped,Amazon,Amazon.in,Expedited,T-shirt,XS,Shipped,1,INR,1199.0,Halol,Gujarat,389350.0,IN,False,Unknown
128975,128974,408-7436540-8728312,05-31-22,Shipped,Amazon,Amazon.in,Expedited,T-shirt,S,Shipped,1,INR,696.0,Raipur,CHHATTISGARH,492014.0,IN,False,Unknown

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128976 entries, 0 to 128975
Data columns (total 19 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   index               128976 non-null  int64
 1   Order ID            128976 non-null  object
 2   Date                128976 non-null  object
 3   Status              128976 non-null  object
 4   Fulfilment          128976 non-null  object
 5   Sales Channel       128976 non-null  object
 6   ship-service-level  128976 non-null  object
 7   Category            128976 non-null  object
 8   Size                128976 non-null  object
 9   Courier Status      128976 non-null  object
 10  Qty                 128976 non-null  int64
 11  currency            121176 non-null  object
 12  Amount              128976 non-null  float64
 13  ship-city           128941 non-null  object
 14  ship-state          128941 non-null  object
 15  ship-postal-code    128941 non-null  float64
 16  ship-country        128941 non-null  object
 17  B2B                 128976 non-null  bool
 18  fulfilled-by        128976 non-null  object
dtypes: bool(1), float64(2), int64(2), object(14)
memory usage: 17.8+ MB

In [12]:
df['Date']=pd.to_datetime(df['Date'],format='%m-%d-%y')

In [14]:
df.drop_duplicates(inplace=True)

In [49]:
df.isnull().sum()

index                    0
Order ID                 0
Date                     0
Status                   0
Fulfilment               0
Sales Channel            0
ship-service-level       0
Category                 0
Size                     0
Courier Status           0
Qty                      0
currency              7800
Amount                   0
ship-city               35
ship-state              35
ship-postal-code        35
ship-country            35
B2B                      0
fulfilled-by             0
dtype: int64

In [49]:
df.isnull().sum()

index                    0
Order ID                 0
Date                     0
Status                   0
Fulfilment               0
Sales Channel            0
ship-service-level       0
Category                 0
Size                     0
Courier Status           0
Qty                      0
currency              7800
Amount                   0
ship-city               35
ship-state              35
ship-postal-code        35
ship-country            35
B2B                      0
fulfilled-by             0
dtype: int64

In [37]:
df.drop(columns=['New','PendingS'],inplace=True)

In [46]:
df['fulfilled-by'].fillna('Unknown',inplace=True)

C:\Users\prabh\AppData\Local\Temp\ipykernel_26824\1751366314.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['fulfilled-by'].fillna('Unknown',inplace=True)

In [25]:
df['Amount']=df['Amount'].fillna(df['Amount'].mean())

C:\Users\prabh\AppData\Local\Temp\ipykernel_26824\2246979497.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Amount']=df['Amount'].fillna(df['Amount'].mean())

In [29]:
df['Amount'].dtype

dtype('float64')

In [44]:
df['Amount'].isnull().sum()

0

In [43]:
df['Amount'].head(10)

0    647.62
1    406.00
2    329.00
3    753.33
4    574.00
5    824.00
6    653.00
7    399.00
8    605.00
9    363.00
Name: Amount, dtype: float64

In [41]:
df['Amount'].describe()

count    121176.000000
mean        648.562176
std         281.185041
min           0.000000
25%         449.000000
50%         605.000000
75%         788.000000
max        5584.000000
Name: Amount, dtype: float64

In [42]:
df['Amount'] = df['Amount'].fillna(df['Amount'].median())

In [55]:
df.isnull().sum()

index                 0
Order ID              0
Date                  0
Status                0
Fulfilment            0
Sales Channel         0
ship-service-level    0
Category              0
Size                  0
Courier Status        0
Qty                   0
Amount                0
ship-city             0
ship-state            0
ship-postal-code      0
ship-country          0
B2B                   0
fulfilled-by          0
dtype: int64

In [51]:
df=df.dropna(subset=['ship-city','ship-state','ship-postal-code','ship-country'])

In [54]:
df.drop(columns=['currency'],inplace=True)

In [68]:
df['ship-state'].unique()

array(['MAHARASHTRA', 'KARNATAKA', 'PUDUCHERRY', 'TAMIL NADU',
       'UTTAR PRADESH', 'CHANDIGARH', 'TELANGANA', 'ANDHRA PRADESH',
       'RAJASTHAN', 'DELHI', 'HARYANA', 'ASSAM', 'JHARKHAND',
       'CHHATTISGARH', 'ODISHA', 'KERALA', 'MADHYA PRADESH',
       'WEST BENGAL', 'NAGALAND', 'GUJARAT', 'UTTARAKHAND', 'BIHAR',
       'JAMMU & KASHMIR', 'PUNJAB', 'HIMACHAL PRADESH',
       'ARUNACHAL PRADESH', 'GOA', 'MEGHALAYA', 'MANIPUR', 'TRIPURA',
       'LADAKH', 'DADRA AND NAGAR', 'SIKKIM', 'ANDAMAN & NICOBAR',
       'RAJSHTHAN', 'MIZORAM', 'LAKSHADWEEP', 'APO'], dtype=object)

In [58]:
df['ship-city'].unique()

array(['MUMBAI', 'BENGALURU', 'NAVI MUMBAI', ...,
       'GULABPURA, Distt BHILWARA', 'Prayagraj (ALLAHABAD)', 'Halol'],
      dtype=object)

In [60]:
df['ship-state']=df['ship-state'].str.upper()

In [62]:
df['ship-state']=df['ship-state'].str.strip()

In [64]:
df['ship-state']=df['ship-state'].replace({'ORISSA':'ODISHA','PB':'PUNJAB','PUNJAB/MOHALI/ZIRAKPUR':'PUNJAB','RJ':'RAJASTHAN','RAJSTHAN':'RAJASTHAN',
  'RAJSTHAN':'RAJASTHAN','NEW DELHI':'DELHI','NL':'NAGALAND','AR':'ARUNACHAL PRADESH','PONDICHERRY':'PUDUCHERRY'})

Top Sales by State

In [69]:
top_state_sales=df.groupby('ship-state')['Amount'].sum().sort()_values(ascending=False)top_state_sales.head(15)

SyntaxError: invalid syntax (2308372141.py, line 1)

In [72]:
top_state_sales = df.groupby('ship-state')['Amount'].sum().sort_values(ascending=False)
top_state_sales.head(60)

ship-state
MAHARASHTRA          14059073.05
KARNATAKA            11045764.22
TELANGANA             7334888.08
UTTAR PRADESH         7241397.08
TAMIL NADU            6927557.30
DELHI                 4635882.41
KERALA                4086129.58
WEST BENGAL           3758892.82
ANDHRA PRADESH        3444734.86
HARYANA               3017085.99
GUJARAT               2929545.82
RAJASTHAN             1870502.16
MADHYA PRADESH        1692463.98
BIHAR                 1505236.32
ODISHA                1471599.39
PUNJAB                1281468.89
ASSAM                 1088229.20
UTTARAKHAND           1039765.55
JHARKHAND              983093.21
GOA                    671903.85
CHHATTISGARH           596816.83
HIMACHAL PRADESH       542543.51
JAMMU & KASHMIR        489058.74
CHANDIGARH             221468.67
MANIPUR                221060.99
PUDUCHERRY             206029.24
ANDAMAN & NICOBAR      165894.62
SIKKIM                 149903.66
NAGALAND               148080.67
MEGHALAYA              125921.81
ARUNACHAL PRADESH      102500.00
TRIPURA                 98598.40
DADRA AND NAGAR         46978.92
MIZORAM                 43763.71
LADAKH                  38993.43
LAKSHADWEEP              3175.29
RAJSHTHAN                1731.00
APO                       605.00
Name: Amount, dtype: float64

In [73]:
df['ship-city'].unique()

array(['MUMBAI', 'BENGALURU', 'NAVI MUMBAI', ...,
       'GULABPURA, Distt BHILWARA', 'Prayagraj (ALLAHABAD)', 'Halol'],
      dtype=object)

In [75]:
df.to_csv("clean_amazon_sales.csv",index=False)

In [76]:
import os 
os.getcwd()

'C:\\Users\\prabh'

In [77]:
df2=pd.read_csv("clean_amazon_sales.csv")

In [78]:
df2.head()

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Category,Size,Courier Status,Qty,Amount,ship-city,ship-state,ship-postal-code,ship-country,B2B,fulfilled-by
0,0,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Standard,T-shirt,S,On the Way,0,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,False,Easy Ship
1,1,171-9198151-1101146,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,Shirt,3XL,Shipped,1,406.00,BENGALURU,KARNATAKA,560085.0,IN,False,Easy Ship
2,2,404-0687676-7273146,04-30-22,Shipped,Amazon,Amazon.in,Expedited,Shirt,XL,Shipped,1,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,True,Unknown
3,3,403-9615377-8133951,04-30-22,Cancelled,Merchant,Amazon.in,Standard,Blazzer,L,On the Way,0,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,False,Easy Ship
4,4,407-1069790-7240320,04-30-22,Shipped,Amazon,Amazon.in,Expedited,Trousers,3XL,Shipped,1,574.00,CHENNAI,TAMIL NADU,600073.0,IN,False,Unknown